services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    environment:
      TELEGRAM_BOT_TOKEN: "8075517888:AAG6a1zUnd0BOoEaSkWbbh5f2Xin40BQfGY"
    restart: always
    depends_on:
      - logstash
    ports:
      - "9091:9091" 

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_NAME: kibana
      SERVER_PUBLICBASEURL: "http://localhost:5601"
      XPACK_SECURITY_ENABLED: "false"
      SERVER_CROSS_ORIGIN_OPENER_POLICY: "unsafe-none"
      SERVER_CROSS_ORIGIN_EMBEDDER_POLICY: "unsafe-none"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
